services:
  api:
    build: .
    container_name: tasks-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - name=value
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=tasks

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: tasks-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
    ports:
      - "3306:3306"
